### ISSUE TITLE
request 403

### ISSUE THREAD

**Issue by zhu18339086032** [JesuisTong/joker_cli#1]
![image](https://github.com/user-attachments/assets/2ace65b6-a2c7-437a-8e99-df526dc5fbf8)

**Comment by zhu18339086032** [comment]
![image](https://github.com/user-attachments/assets/1faad335-90b4-4b27-8111-7c5c406ea4ab)

**Comment by JesuisTong** [comment]
![image](https://github.com/user-attachments/assets/cacee771-fccf-4a33-8145-e61df1db68ac)

sth update.

**Comment by zhu18339086032** [comment]
Thank you, will you continue to update the code？

**Comment by zhu18339086032** [comment]
ok 
![image](https://github.com/user-attachments/assets/2e21cc7b-07f9-407f-b16d-8d7404906009)
