### ISSUE TITLE
deae，Can you give a basic command of mining,

### ISSUE THREAD

**Issue by zhu18339086032** [JesuisTong/joker_cli#2]
![image](https://github.com/user-attachments/assets/d888991f-d374-4c27-a411-268f75f96fec)

**Comment by zhu18339086032** [comment]
![image](https://github.com/user-attachments/assets/080cc81a-e652-4dd1-a68d-2beb2a6238b7)

**Comment by JesuisTong** [comment]
Simple example below:
`joker_cli.exe --cookie <your cookie> --authorization <auth> mine --threads <number>`
